name: Monastery360
options:
  bundleIdPrefix: com.monastery360
  deploymentTarget:
    iOS: 17.0
  groupSortPosition: top
  xcodeVersion: 15.0
targets:
  Monastery360:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: App
      - path: GoogleService-Info.plist
    entitlements:
      path: Monastery360.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monastery360.app
        INFOPLIST_FILE: Info.plist
        DEVELOPMENT_TEAM: "" # User to fill if needed, or automatic
        CODE_SIGN_STYLE: Automatic
        marketingVersion: 1.0.0
        currentProjectVersion: 1
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseAnalytics
      - package: GoogleSignIn
        product: GoogleSignIn
  Monastery360Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: App
        excludes: ["**/*"] # Exclude app sources, we will just import the module
      - path: Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.monastery360.tests
        INFOPLIST_FILE: Tests/Info.plist
    dependencies:
      - target: Monastery360
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 7.0.0
